kind: pipeline
type: docker
name: pr

steps:
  - name: echo
    commands:
      - echo "saaaaaay"
  - name: code-build
     image: node:10
     commands:
       - yarn
       - yarn run build
  - name: docker-build
    image: plugins/ecr
    settings:
      access_key: $${GCR_TOKEN}
      secret_key: $${GCR_SECRET}
      repo: ecs-cicd-test
      registry: 456797426009.dkr.ecr.us-west-2.amazonaws.com
trigger:
  branch:
    - master
    - feature/*
  event:
    - push
